# Generated by Django 3.1.7 on 2021-04-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
