# Generated by Django 3.1.7 on 2021-04-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_detalleventa_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(max_length=25),
        ),
    ]
