# Generated by Django 3.1.7 on 2021-04-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20210412_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
