# Generated by Django 3.1.7 on 2021-04-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0010_auto_20210414_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Tamaño', 'verbose_name_plural': 'Tamaños'},
        ),
        migrations.AddField(
            model_name='color',
            name='codigo',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='coloresproducto', to='producto.Color'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='sizesproducto', to='producto.Size'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.ManyToManyField(blank=True, related_name='tallasproducto', to='producto.Talla'),
        ),
    ]
