# Generated by Django 3.1.7 on 2021-04-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0011_auto_20210414_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='codigo',
            field=models.CharField(max_length=7),
        ),
    ]
