# Generated by Django 3.1.7 on 2021-04-17 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0013_favorito_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorito',
            name='created_at',
        ),
    ]
