# Generated by Django 3.1.7 on 2021-04-17 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0014_remove_favorito_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
    ]
