# Generated by Django 3.1.7 on 2021-04-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0017_auto_20210420_0018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
