# Generated by Django 3.1.7 on 2021-04-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_publicacion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=150),
        ),
    ]
