# Generated by Django 3.1.7 on 2021-04-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_auto_20210416_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='tags_pubs', to='publicaciones.Etiqueta', verbose_name='Etiquetas'),
        ),
    ]
